### ISSUE TITLE
Change WebUI to https://

### ISSUE THREAD

**Issue by archedraft** [needo37/plex#17]
Would there be anyway for you to change the WebUI Docker link to use https:// instead of http://?

**Comment by needo37** [comment]
I don't specify the WebUI link at all. Can you please provide further details?

**Comment by archedraft** [comment]
The newest version of Plex now supports https and I was wondering if that could be added to the docker WebUI link but the more I think about it, it doesn't really make sense. You are accessing Plex through your local network with the WebUI link anyways so why go through the trouble?

**Comment by needo37** [comment]
Yes and the docker does not have ports exposed. It uses bridge mode so
there is nothing new to expose.
